version: "3.1"

services:
  frontend:
    container_name: "frontend-portfolio"
    restart: "unless-stopped"
    build:
      context: "."
      dockerfile: "frontend/Dockerfile"
      target: "development"
    command: "npm run start"
    volumes:
      - "./frontend:/app:rw"
    env_file:
      - "./frontend/.env"
    ports:
      - "3000"
    depends_on:
      - "backend"
    networks:
      - "nginx-proxy-manager_default"

  backend:
    container_name: "backend-portfolio"
    restart: "unless-stopped"
    build:
      context: "."
      dockerfile: "backend/Dockerfile"
      target: "development"
    command: "npm run start"
    volumes:
      - "./backend/src:/app/src:rw"
    env_file:
      - "./backend/.env"
    ports:
      - "3001"
    depends_on:
      - "redis"
      - "mongo"
    networks:
      - "redis_net"
      - "mongo_net"
      - "nginx-proxy-manager_default"

  redis:
    container_name: "redis-portfolio"
    image: "redis:latest"
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - "redis_net"

  mongo:
    container_name: "mongodb-portfolio"
    image: "mongo:latest"
    restart: "unless-stopped"
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - "mongo_net"

networks:
  redis_net:
  mongo_net:
  backend_net:
  frontend_net:
  nginx-proxy-manager_default:
    external: true
